<?php

class DealsTableSeeder
  extends DatabaseSeeder
{
  public function run()
  {

    $faker = Faker\Factory::create();

    $deals = [

      [
        "dealer_id"         => "1",
        "campaign_id"       => "1",
        "customer_number"   => "1010",
        "deal_number"       => "2010",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => $faker->phoneNumber,
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3010",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "campaign_id"       => "2",
        "customer_number"   => "1011",
        "deal_number"       => "2011",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5511",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3011",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "campaign_id"       => "2",
        "customer_number"   => "1012",
        "deal_number"       => "2012",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5512",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3012",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1013",
        "deal_number"       => "2013",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5513",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3013",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Sienna",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1014",
        "deal_number"       => "2014",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5514",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3014",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Sienna",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1015",
        "deal_number"       => "2015",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5515",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3015",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1016",
        "deal_number"       => "2016",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5516",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3016",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1017",
        "deal_number"       => "2017",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5517",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3017",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1018",
        "deal_number"       => "2018",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5518",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3018",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1019",
        "deal_number"       => "2019",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5519",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3019",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1020",
        "deal_number"       => "2020",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5520",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3020",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1021",
        "deal_number"       => "2021",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5521",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3021",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1022",
        "deal_number"       => "2022",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5522",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3022",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1023",
        "deal_number"       => "2023",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5523",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3023",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1024",
        "deal_number"       => "2024",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5524",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3024",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1025",
        "deal_number"       => "2025",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5525",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3025",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Sienna",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1026",
        "deal_number"       => "2026",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5526",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3026",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1027",
        "deal_number"       => "2027",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5527",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3027",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1028",
        "deal_number"       => "2028",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5528",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3028",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1029",
        "deal_number"       => "2029",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5529",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3029",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Sienna",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1030",
        "deal_number"       => "2030",
        "name"              => $faker->name,
        "address_1"         => $faker->streetAddress,
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5530",
        "fax"               => "",
        "email"             => $faker->email,
        "stock_number"      => "3030",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1031",
        "deal_number"       => "2031",
        "name"              => "Client 31",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5531",
        "fax"               => "",
        "email"             => "client31@email.com",
        "stock_number"      => "3031",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1032",
        "deal_number"       => "2032",
        "name"              => "Client 32",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5532",
        "fax"               => "",
        "email"             => "client32@email.com",
        "stock_number"      => "3032",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1033",
        "deal_number"       => "2033",
        "name"              => "Client 33",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5533",
        "fax"               => "",
        "email"             => "client33@email.com",
        "stock_number"      => "3033",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Sienna",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1034",
        "deal_number"       => "2034",
        "name"              => "Client 34",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5534",
        "fax"               => "",
        "email"             => "client34@email.com",
        "stock_number"      => "3034",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1035",
        "deal_number"       => "2035",
        "name"              => "Client 35",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5535",
        "fax"               => "",
        "email"             => "client35@email.com",
        "stock_number"      => "3035",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1036",
        "deal_number"       => "2036",
        "name"              => "Client 36",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5536",
        "fax"               => "",
        "email"             => "client36@email.com",
        "stock_number"      => "3036",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1037",
        "deal_number"       => "2037",
        "name"              => "Client 37",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5537",
        "fax"               => "",
        "email"             => "client37@email.com",
        "stock_number"      => "3037",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Sienna",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1038",
        "deal_number"       => "2038",
        "name"              => "Client 38",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5538",
        "fax"               => "",
        "email"             => "client38@email.com",
        "stock_number"      => "3038",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1039",
        "deal_number"       => "2039",
        "name"              => "Client 39",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5539",
        "fax"               => "",
        "email"             => "client39@email.com",
        "stock_number"      => "3039",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1040",
        "deal_number"       => "2040",
        "name"              => "Client 40",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5540",
        "fax"               => "",
        "email"             => "client40@email.com",
        "stock_number"      => "3040",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Sienna",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1041",
        "deal_number"       => "2041",
        "name"              => "Client 41",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5541",
        "fax"               => "",
        "email"             => "client41@email.com",
        "stock_number"      => "3041",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1042",
        "deal_number"       => "2042",
        "name"              => "Client 42",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5542",
        "fax"               => "",
        "email"             => "client42@email.com",
        "stock_number"      => "3042",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1043",
        "deal_number"       => "2043",
        "name"              => "Client 43",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5543",
        "fax"               => "",
        "email"             => "client43@email.com",
        "stock_number"      => "3043",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1044",
        "deal_number"       => "2044",
        "name"              => "Client 44",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5544",
        "fax"               => "",
        "email"             => "client44@email.com",
        "stock_number"      => "3044",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1045",
        "deal_number"       => "2045",
        "name"              => "Client 45",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5545",
        "fax"               => "",
        "email"             => "client45@email.com",
        "stock_number"      => "3045",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1046",
        "deal_number"       => "2046",
        "name"              => "Client 46",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5546",
        "fax"               => "",
        "email"             => "client46@email.com",
        "stock_number"      => "3046",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1047",
        "deal_number"       => "2047",
        "name"              => "Client 47",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5547",
        "fax"               => "",
        "email"             => "client47@email.com",
        "stock_number"      => "3047",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1048",
        "deal_number"       => "2048",
        "name"              => "Client 48",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5548",
        "fax"               => "",
        "email"             => "client48@email.com",
        "stock_number"      => "3048",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1049",
        "deal_number"       => "2049",
        "name"              => "Client 49",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5549",
        "fax"               => "",
        "email"             => "client49@email.com",
        "stock_number"      => "3049",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1050",
        "deal_number"       => "2050",
        "name"              => "Client 50",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5550",
        "fax"               => "",
        "email"             => "client50@email.com",
        "stock_number"      => "3050",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Sienna",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1051",
        "deal_number"       => "2051",
        "name"              => "Client 51",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5551",
        "fax"               => "",
        "email"             => "client51@email.com",
        "stock_number"      => "3051",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1052",
        "deal_number"       => "2052",
        "name"              => "Client 52",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5552",
        "fax"               => "",
        "email"             => "client52@email.com",
        "stock_number"      => "3052",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1053",
        "deal_number"       => "2053",
        "name"              => "Client 53",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5553",
        "fax"               => "",
        "email"             => "client53@email.com",
        "stock_number"      => "3053",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1054",
        "deal_number"       => "2054",
        "name"              => "Client 54",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5554",
        "fax"               => "",
        "email"             => "client54@email.com",
        "stock_number"      => "3054",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1055",
        "deal_number"       => "2055",
        "name"              => "Client 55",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5555",
        "fax"               => "",
        "email"             => "client55@email.com",
        "stock_number"      => "3055",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1056",
        "deal_number"       => "2056",
        "name"              => "Client 56",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5556",
        "fax"               => "",
        "email"             => "client56@email.com",
        "stock_number"      => "3056",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1057",
        "deal_number"       => "2057",
        "name"              => "Client 57",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5557",
        "fax"               => "",
        "email"             => "client57@email.com",
        "stock_number"      => "3057",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1058",
        "deal_number"       => "2058",
        "name"              => "Client 58",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5558",
        "fax"               => "",
        "email"             => "client58@email.com",
        "stock_number"      => "3058",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1059",
        "deal_number"       => "2059",
        "name"              => "Client 59",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5559",
        "fax"               => "",
        "email"             => "client59@email.com",
        "stock_number"      => "3059",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1060",
        "deal_number"       => "2060",
        "name"              => "Client 60",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5560",
        "fax"               => "",
        "email"             => "client60@email.com",
        "stock_number"      => "3060",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1061",
        "deal_number"       => "2061",
        "name"              => "Client 61",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5561",
        "fax"               => "",
        "email"             => "client61@email.com",
        "stock_number"      => "3061",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1062",
        "deal_number"       => "2062",
        "name"              => "Client 62",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5562",
        "fax"               => "",
        "email"             => "client62@email.com",
        "stock_number"      => "3062",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1063",
        "deal_number"       => "2063",
        "name"              => "Client 63",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5563",
        "fax"               => "",
        "email"             => "client63@email.com",
        "stock_number"      => "3063",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1064",
        "deal_number"       => "2064",
        "name"              => "Client 64",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5564",
        "fax"               => "",
        "email"             => "client64@email.com",
        "stock_number"      => "3064",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1065",
        "deal_number"       => "2065",
        "name"              => "Client 65",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5565",
        "fax"               => "",
        "email"             => "client65@email.com",
        "stock_number"      => "3065",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1066",
        "deal_number"       => "2066",
        "name"              => "Client 66",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5566",
        "fax"               => "",
        "email"             => "client66@email.com",
        "stock_number"      => "3066",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1067",
        "deal_number"       => "2067",
        "name"              => "Client 67",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5567",
        "fax"               => "",
        "email"             => "client67@email.com",
        "stock_number"      => "3067",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1068",
        "deal_number"       => "2068",
        "name"              => "Client 68",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5568",
        "fax"               => "",
        "email"             => "client68@email.com",
        "stock_number"      => "3068",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1069",
        "deal_number"       => "2069",
        "name"              => "Client 69",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5569",
        "fax"               => "",
        "email"             => "client69@email.com",
        "stock_number"      => "3069",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1070",
        "deal_number"       => "2070",
        "name"              => "Client 70",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5570",
        "fax"               => "",
        "email"             => "client70@email.com",
        "stock_number"      => "3070",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1071",
        "deal_number"       => "2071",
        "name"              => "Client 71",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5571",
        "fax"               => "",
        "email"             => "client71@email.com",
        "stock_number"      => "3071",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1072",
        "deal_number"       => "2072",
        "name"              => "Client 72",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5572",
        "fax"               => "",
        "email"             => "client72@email.com",
        "stock_number"      => "3072",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1073",
        "deal_number"       => "2073",
        "name"              => "Client 73",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5573",
        "fax"               => "",
        "email"             => "client73@email.com",
        "stock_number"      => "3073",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1074",
        "deal_number"       => "2074",
        "name"              => "Client 74",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5574",
        "fax"               => "",
        "email"             => "client74@email.com",
        "stock_number"      => "3074",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1075",
        "deal_number"       => "2075",
        "name"              => "Client 75",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5575",
        "fax"               => "",
        "email"             => "client75@email.com",
        "stock_number"      => "3075",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1076",
        "deal_number"       => "2076",
        "name"              => "Client 76",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5576",
        "fax"               => "",
        "email"             => "client76@email.com",
        "stock_number"      => "3076",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1077",
        "deal_number"       => "2077",
        "name"              => "Client 77",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5577",
        "fax"               => "",
        "email"             => "client77@email.com",
        "stock_number"      => "3077",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1078",
        "deal_number"       => "2078",
        "name"              => "Client 78",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5578",
        "fax"               => "",
        "email"             => "client78@email.com",
        "stock_number"      => "3078",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1079",
        "deal_number"       => "2079",
        "name"              => "Client 79",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5579",
        "fax"               => "",
        "email"             => "client79@email.com",
        "stock_number"      => "3079",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1080",
        "deal_number"       => "2080",
        "name"              => "Client 80",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5580",
        "fax"               => "",
        "email"             => "client80@email.com",
        "stock_number"      => "3080",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1081",
        "deal_number"       => "2081",
        "name"              => "Client 81",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5581",
        "fax"               => "",
        "email"             => "client81@email.com",
        "stock_number"      => "3081",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1082",
        "deal_number"       => "2082",
        "name"              => "Client 82",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5582",
        "fax"               => "",
        "email"             => "client82@email.com",
        "stock_number"      => "3082",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1083",
        "deal_number"       => "2083",
        "name"              => "Client 83",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5583",
        "fax"               => "",
        "email"             => "client83@email.com",
        "stock_number"      => "3083",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1084",
        "deal_number"       => "2084",
        "name"              => "Client 84",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5584",
        "fax"               => "",
        "email"             => "client84@email.com",
        "stock_number"      => "3084",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1085",
        "deal_number"       => "2085",
        "name"              => "Client 85",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5585",
        "fax"               => "",
        "email"             => "client85@email.com",
        "stock_number"      => "3085",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Sienna",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1086",
        "deal_number"       => "2086",
        "name"              => "Client 86",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5586",
        "fax"               => "",
        "email"             => "client86@email.com",
        "stock_number"      => "3086",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1087",
        "deal_number"       => "2087",
        "name"              => "Client 87",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5587",
        "fax"               => "",
        "email"             => "client87@email.com",
        "stock_number"      => "3087",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "1088",
        "deal_number"       => "2088",
        "name"              => "Client 88",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5588",
        "fax"               => "",
        "email"             => "client88@email.com",
        "stock_number"      => "3088",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1089",
        "deal_number"       => "2089",
        "name"              => "Client 89",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5589",
        "fax"               => "",
        "email"             => "client89@email.com",
        "stock_number"      => "3089",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1090",
        "deal_number"       => "2090",
        "name"              => "Client 90",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5590",
        "fax"               => "",
        "email"             => "client90@email.com",
        "stock_number"      => "3090",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1091",
        "deal_number"       => "2091",
        "name"              => "Client 91",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5591",
        "fax"               => "",
        "email"             => "client91@email.com",
        "stock_number"      => "3091",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1092",
        "deal_number"       => "2092",
        "name"              => "Client 92",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5592",
        "fax"               => "",
        "email"             => "client92@email.com",
        "stock_number"      => "3092",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1093",
        "deal_number"       => "2093",
        "name"              => "Client 93",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5593",
        "fax"               => "",
        "email"             => "client93@email.com",
        "stock_number"      => "3093",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1094",
        "deal_number"       => "2094",
        "name"              => "Client 94",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5594",
        "fax"               => "",
        "email"             => "client94@email.com",
        "stock_number"      => "3094",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1095",
        "deal_number"       => "2095",
        "name"              => "Client 95",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5595",
        "fax"               => "",
        "email"             => "client95@email.com",
        "stock_number"      => "3095",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1096",
        "deal_number"       => "2096",
        "name"              => "Client 96",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5596",
        "fax"               => "",
        "email"             => "client96@email.com",
        "stock_number"      => "3096",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1097",
        "deal_number"       => "2097",
        "name"              => "Client 97",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5597",
        "fax"               => "",
        "email"             => "client97@email.com",
        "stock_number"      => "3097",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Sienna",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "1098",
        "deal_number"       => "2098",
        "name"              => "Client 98",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5598",
        "fax"               => "",
        "email"             => "client98@email.com",
        "stock_number"      => "3098",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "1099",
        "deal_number"       => "2099",
        "name"              => "Client 99",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-5599",
        "fax"               => "",
        "email"             => "client99@email.com",
        "stock_number"      => "3099",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "10100",
        "deal_number"       => "20100",
        "name"              => "Client 100",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-55100",
        "fax"               => "",
        "email"             => "client100@email.com",
        "stock_number"      => "30100",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Avalon",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "10101",
        "deal_number"       => "20101",
        "name"              => "Client 101",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-55101",
        "fax"               => "",
        "email"             => "client101@email.com",
        "stock_number"      => "30101",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "10102",
        "deal_number"       => "20102",
        "name"              => "Client 102",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-55102",
        "fax"               => "",
        "email"             => "client102@email.com",
        "stock_number"      => "30102",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "10103",
        "deal_number"       => "20103",
        "name"              => "Client 103",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-55103",
        "fax"               => "",
        "email"             => "client103@email.com",
        "stock_number"      => "30103",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Sienna",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "10104",
        "deal_number"       => "20104",
        "name"              => "Client 104",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-55104",
        "fax"               => "",
        "email"             => "client104@email.com",
        "stock_number"      => "30104",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Camry",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "10105",
        "deal_number"       => "20105",
        "name"              => "Client 105",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-55105",
        "fax"               => "",
        "email"             => "client105@email.com",
        "stock_number"      => "30105",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Sienna",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "3",
        "customer_number"   => "10106",
        "deal_number"       => "20106",
        "name"              => "Client 106",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-55106",
        "fax"               => "",
        "email"             => "client106@email.com",
        "stock_number"      => "30106",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-3-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "10107",
        "deal_number"       => "20107",
        "name"              => "Client 107",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-55107",
        "fax"               => "",
        "email"             => "client107@email.com",
        "stock_number"      => "30107",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Yaris",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "10108",
        "deal_number"       => "20108",
        "name"              => "Client 108",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-55108",
        "fax"               => "",
        "email"             => "client108@email.com",
        "stock_number"      => "30108",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2013-10-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "2",
        "customer_number"   => "10109",
        "deal_number"       => "20109",
        "name"              => "Client 109",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-55109",
        "fax"               => "",
        "email"             => "client109@email.com",
        "stock_number"      => "30109",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Corolla",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],


      [
        "dealer_id"         => "1",
        "customer_number"   => "10110",
        "deal_number"       => "20110",
        "name"              => "Client 110",
        "address_1"         => "Address 1",
        "address_2"         => "Address 2",
        "city"              => "City",
        "state"             => "FL",
        "zip"               => "Zip",
        "phone"             => "305-255-55110",
        "fax"               => "",
        "email"             => "client110@email.com",
        "stock_number"      => "30110",
        "vehicle_year"      => "2013",
        "vehicle_make"      => "Toyota",
        "vehicle_model"     => "Tacoma",
        "vehicle_color"     => "Black",
        "purchase_date"     => "2014-1-1",
        "last_visit"        => "",
      ],
    ];

    foreach ($deals as $deal) {
      Deal::create($deal);
    }
  }
}

