<?php

class DealerGroupsTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
        
		\DB::table('dealer_groups')->insert(array (
			0 => 
			array (
				'id' => '1',
				'name' => 'Test Dealer Group',
				'address_1' => 'Address 1',
				'address_2' => 'Address 2',
				'city' => 'City',
				'state' => 'ST',
				'zip' => 'Zip-Code',
				'phone' => '305-PHONE',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '1',
				'active' => '1',
				'created_at' => '2014-07-18 05:54:56',
				'updated_at' => '2014-07-19 05:26:11',
			),
			1 => 
			array (
				'id' => '4',
				'name' => 'Ivory Auto Group',
				'address_1' => '4200 Jonesboro Road',
				'address_2' => '',
				'city' => 'Union City',
				'state' => 'GA',
				'zip' => '30291',
			'phone' => '(770) 969-1001',
				'fax' => '',
				'email' => '',
				'contact' => 'David Karangu',
			'contact_phone' => '(770) 969-1001',
				'contact_email' => '',
				'added_by_id' => '1',
				'active' => '1',
				'created_at' => '2014-08-06 11:42:54',
				'updated_at' => '2014-08-06 11:42:54',
			),
			2 => 
			array (
				'id' => '5',
				'name' => 'Florida Fine Cars',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '1',
				'active' => '1',
				'created_at' => '2014-08-30 17:00:57',
				'updated_at' => '2014-08-30 17:00:57',
			),
			3 => 
			array (
				'id' => '6',
				'name' => 'Hollywood Auto Group',
				'address_1' => '',
				'address_2' => ' ',
				'city' => 'Hollywood',
				'state' => 'FL',
				'zip' => '33024',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '1',
				'active' => '1',
				'created_at' => '2014-09-06 10:17:17',
				'updated_at' => '2014-09-06 10:19:49',
			),
			4 => 
			array (
				'id' => '7',
				'name' => 'Estabrook Motor Company',
				'address_1' => '',
				'address_2' => '',
				'city' => 'Pascagoula',
				'state' => 'FL',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '1',
				'active' => '1',
				'created_at' => '2014-09-08 19:09:48',
				'updated_at' => '2014-09-08 19:09:48',
			),
			5 => 
			array (
				'id' => '8',
				'name' => 'Wallace Automotive Group',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '1',
				'active' => '1',
				'created_at' => '2014-09-08 19:24:10',
				'updated_at' => '2014-09-08 19:24:10',
			),
			6 => 
			array (
				'id' => '9',
				'name' => 'Gus Machado Ford',
				'address_1' => '',
				'address_2' => '',
				'city' => 'Hialeah',
				'state' => 'FL',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-09-09 08:55:23',
				'updated_at' => '2014-09-09 08:55:23',
			),
			7 => 
			array (
				'id' => '10',
				'name' => 'Crossroads Automotive Group',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => 'NC',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-09-09 11:44:09',
				'updated_at' => '2014-09-09 11:44:09',
			),
			8 => 
			array (
				'id' => '11',
				'name' => 'Team Gunther Group',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-09-09 11:44:57',
				'updated_at' => '2014-09-09 11:44:57',
			),
			9 => 
			array (
				'id' => '12',
				'name' => 'SEAM Auto Group',
				'address_1' => '',
				'address_2' => '',
				'city' => 'Daphne',
				'state' => 'AL',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-09-09 11:49:54',
				'updated_at' => '2014-09-09 11:49:54',
			),
			10 => 
			array (
				'id' => '14',
				'name' => 'Gunther Motors',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-09-09 11:58:24',
				'updated_at' => '2014-09-09 11:58:24',
			),
			11 => 
			array (
				'id' => '15',
				'name' => 'Murphy Auto Group',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => 'FL',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-09-09 12:34:31',
				'updated_at' => '2014-09-09 12:34:31',
			),
			12 => 
			array (
				'id' => '16',
				'name' => 'Priority Auto Group',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-09-09 14:46:57',
				'updated_at' => '2014-09-09 14:46:57',
			),
			13 => 
			array (
				'id' => '17',
				'name' => 'Lakeland Automall ',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-09-09 14:47:29',
				'updated_at' => '2014-09-09 14:47:29',
			),
			14 => 
			array (
				'id' => '18',
				'name' => 'Savannah Auto Group',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-09-09 21:12:08',
				'updated_at' => '2014-09-09 21:12:08',
			),
			15 => 
			array (
				'id' => '19',
				'name' => 'South Motors Group',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-09-09 21:15:20',
				'updated_at' => '2014-09-09 21:15:20',
			),
			16 => 
			array (
				'id' => '20',
				'name' => 'Plano Auto Group',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-09-09 21:23:34',
				'updated_at' => '2014-09-09 21:23:34',
			),
			17 => 
			array (
				'id' => '21',
				'name' => 'Phill Smith Automotive Group',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '3',
				'active' => '1',
				'created_at' => '2014-09-10 15:47:46',
				'updated_at' => '2014-09-10 15:47:46',
			),
			18 => 
			array (
				'id' => '22',
				'name' => 'Ed Morse',
				'address_1' => '1240 N Federal Hwy',
				'address_2' => '',
				'city' => 'Fort Lauderdale',
				'state' => 'FL',
				'zip' => '33304',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '17',
				'active' => '1',
				'created_at' => '2014-09-23 16:37:38',
				'updated_at' => '2014-09-23 16:37:38',
			),
			19 => 
			array (
				'id' => '23',
				'name' => 'Rick Case',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => 'FL',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '17',
				'active' => '1',
				'created_at' => '2014-09-23 19:01:09',
				'updated_at' => '2014-09-23 19:01:09',
			),
			20 => 
			array (
				'id' => '25',
				'name' => 'Coral Springs Auto Mall',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '17',
				'active' => '1',
				'created_at' => '2014-09-23 19:18:50',
				'updated_at' => '2014-09-23 19:18:50',
			),
			21 => 
			array (
				'id' => '26',
				'name' => 'Lester Ariel Mesa',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-09-25 01:36:35',
				'updated_at' => '2014-09-25 01:36:35',
			),
			22 => 
			array (
				'id' => '27',
				'name' => 'Brickell Motors ',
				'address_1' => '',
				'address_2' => '',
				'city' => 'Miami',
				'state' => 'FL',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '16',
				'active' => '1',
				'created_at' => '2014-10-15 15:31:45',
				'updated_at' => '2014-10-15 15:31:45',
			),
			23 => 
			array (
				'id' => '28',
				'name' => 'Napleton Automotive Group',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'email' => '',
				'contact' => '',
				'contact_phone' => '',
				'contact_email' => '',
				'added_by_id' => '19',
				'active' => '1',
				'created_at' => '2014-10-30 23:42:07',
				'updated_at' => '2014-10-30 23:42:07',
			),
			24 => 
			array (
				'id' => '29',
				'name' => 'Volvo of North Miami',
				'address_1' => '19275 N.W. 2nd Ave.',
				'address_2' => '',
				'city' => 'Miami',
				'state' => 'Florida',
				'zip' => '33169',
				'phone' => '305-651-2436',
				'fax' => '',
				'email' => 'dschmidt@volvonorthmiami.net',
				'contact' => 'Tommy',
				'contact_phone' => '617-863-0866',
				'contact_email' => '',
				'added_by_id' => '21',
				'active' => '1',
				'created_at' => '2014-12-04 23:37:25',
				'updated_at' => '2014-12-04 23:37:25',
			),
		));
	}

}
