<?php

class UsersTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('users')->truncate();
        
		\DB::table('users')->insert(array (
			0 => 
			array (
				'id' => '1',
				'dealer_id' => NULL,
				'name' => 'Lester Mesa',
				'initials' => 'LM',
				'username' => 'lester',
				'password' => '$2y$10$xEOpxJ.fOEzy2Ozt4Jl7yei1yKj4fzdiwHCctvS4qyWMQRC4emlGm',
				'email' => 'lester@loyaldriver.com',
				'address_1' => NULL,
				'address_2' => NULL,
				'city' => NULL,
				'state' => NULL,
				'zip' => NULL,
				'phone' => '786-342-3433',
				'fax' => NULL,
				'remember_token' => '1blxBiu5BMmvh2v6DQK3Y8GsjD4oM74pVqV1iShJ0zfDFskVRTfyyjI5WPJP',
				'active' => '1',
				'created_at' => '2014-07-18 05:54:56',
				'updated_at' => '2015-01-03 22:53:42',
			),
			1 => 
			array (
				'id' => '2',
				'dealer_id' => NULL,
				'name' => 'Nick DeNapoli',
				'initials' => 'ND',
				'username' => 'nick',
				'password' => '$2y$10$ZxqzyvEP0.14RbEQRP4F1eLbbsp1.l1YC9JTz5JX62zJN826jeRie',
				'email' => 'nick@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '847-722-4750',
				'fax' => '',
				'remember_token' => '62ivIqbXhJxNZpHEJMEFBGcFJY8V6o5b88He0xuQ1EAq3h9eyWJmSc7idhtO',
				'active' => '1',
				'created_at' => '2014-07-18 05:54:56',
				'updated_at' => '2014-12-23 17:54:03',
			),
			2 => 
			array (
				'id' => '3',
				'dealer_id' => NULL,
				'name' => 'Alex Bezianis',
				'initials' => 'AB',
				'username' => 'alex',
				'password' => '$2y$10$j7NHp9VxBtD5MfpX7yZ6CeFMLEGMcRCaYYlg/QGQ/YjwjYT1thYHC',
				'email' => 'alex@loyaldriver.com',
				'address_1' => NULL,
				'address_2' => NULL,
				'city' => NULL,
				'state' => NULL,
				'zip' => NULL,
				'phone' => '954-345-3246',
				'fax' => NULL,
				'remember_token' => 'du4rYG4PxQfd0jb6t0dBrSTFUZ5MAcijipjEREyGge5qgNPzXWM6bQorpFhr',
				'active' => '1',
				'created_at' => '2014-07-18 05:54:56',
				'updated_at' => '2014-09-10 17:13:25',
			),
			3 => 
			array (
				'id' => '4',
				'dealer_id' => NULL,
				'name' => 'Manager',
				'initials' => NULL,
				'username' => 'manager',
				'password' => '$2y$10$Xnezo2d1ebridQHNQ22IxOyRk8tzBblq3Nu0u5HA7mIQmsBV39glq',
				'email' => 'manager@loyaldriver.com',
				'address_1' => NULL,
				'address_2' => NULL,
				'city' => NULL,
				'state' => NULL,
				'zip' => NULL,
				'phone' => '000-000-0000',
				'fax' => NULL,
				'remember_token' => NULL,
				'active' => '1',
				'created_at' => '2014-07-18 05:54:56',
				'updated_at' => '2014-07-18 05:54:56',
			),
			4 => 
			array (
				'id' => '5',
				'dealer_id' => NULL,
				'name' => 'Agent 1',
				'initials' => NULL,
				'username' => 'agent1',
				'password' => '$2y$10$C72Cz.yJYbMlJqpAYbyiUuyqpQIDcd7hI.pQKAToLvP/jWf2x6cTy',
				'email' => 'agent1@loyaldriver.com',
				'address_1' => NULL,
				'address_2' => NULL,
				'city' => NULL,
				'state' => NULL,
				'zip' => NULL,
				'phone' => '000-000-0000',
				'fax' => NULL,
				'remember_token' => 'aNieq0mhVi1rvnZasF8PBpn1guLs4C86dRCn0LDhSGAFxqaehpXIjezs2BKc',
				'active' => '1',
				'created_at' => '2014-07-18 05:54:56',
				'updated_at' => '2014-09-02 12:11:34',
			),
			5 => 
			array (
				'id' => '6',
				'dealer_id' => NULL,
				'name' => 'Agent 2',
				'initials' => NULL,
				'username' => 'agent2',
				'password' => '$2y$10$yCkz0eF4ADjuBUkyn5c3n.6HZ48hNmfzjixxxwenshx/Hml2qXci2',
				'email' => 'agent2@loyaldriver.com',
				'address_1' => NULL,
				'address_2' => NULL,
				'city' => NULL,
				'state' => NULL,
				'zip' => NULL,
				'phone' => '000-000-0000',
				'fax' => NULL,
				'remember_token' => 'g7qMDPVlDDalymGylXwChHUQ1ZSiERjSBJYEysgc9VTKGSjPj7GVD8d7mjjZ',
				'active' => '1',
				'created_at' => '2014-07-18 05:54:56',
				'updated_at' => '2014-09-02 10:04:27',
			),
			6 => 
			array (
				'id' => '7',
				'dealer_id' => NULL,
				'name' => 'Sales Representative',
				'initials' => NULL,
				'username' => 'sales',
				'password' => '$2y$10$NF58dRjtipgfNvmQnbZ1oeHJjYeeCglZwa.NTeAc0xk/6oBfYbNm6',
				'email' => 'sales@loyaldriver.com',
				'address_1' => NULL,
				'address_2' => NULL,
				'city' => NULL,
				'state' => NULL,
				'zip' => NULL,
				'phone' => '000-000-0000',
				'fax' => NULL,
				'remember_token' => NULL,
				'active' => '1',
				'created_at' => '2014-07-18 05:54:56',
				'updated_at' => '2014-07-18 05:54:56',
			),
			7 => 
			array (
				'id' => '8',
				'dealer_id' => '1',
				'name' => 'Test Dealer 1',
				'initials' => NULL,
				'username' => 'htoyota',
				'password' => '$2y$10$ws6KZmVZ5KZ.j6m2eUz4gOY6J3j262dLpni5Qxv07rtBy8BmnswJy',
				'email' => 'testdealer1@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '000-000-0000',
				'fax' => '',
				'remember_token' => 'E2PneYv3NeQpXJ23WHi7UOdcgUNp7Uak1vhZTlkDHJzyf2bmWtiK1vAcQFwQ',
				'active' => '1',
				'created_at' => '2014-07-18 05:55:06',
				'updated_at' => '2014-09-04 11:47:01',
			),
			8 => 
			array (
				'id' => '9',
				'dealer_id' => '7',
				'name' => 'Test Dealer3',
				'initials' => NULL,
				'username' => 'testdealer3',
				'password' => '$2y$10$ws6KZmVZ5KZ.j6m2eUz4gOY6J3j262dLpni5Qxv07rtBy8BmnswJy',
				'email' => 'testdealer3@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => '4KkyEaaT4A9z0CAlrvo1r5c6DgWadZp9Rdobnd7juhdOEYibH6QBBQyU3vHT',
				'active' => '1',
				'created_at' => '2014-07-19 09:43:58',
				'updated_at' => '2014-08-13 09:22:42',
			),
			9 => 
			array (
				'id' => '10',
				'dealer_id' => '8',
				'name' => 'Kim Robinson',
				'initials' => NULL,
				'username' => 'kimr',
				'password' => '$2y$10$xKWyfEZnFzJOwSoO.Ek6w.Jgdso5Pj1oOkpZOGF27yMgpQYvJstFy',
				'email' => 'kimr@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => '9hW5IzrSWJIrodRK1ZZ2puzD4jnN6kegufUR82ybchU5DJdSwPdtUy4NoEw3',
				'active' => '1',
				'created_at' => '2014-08-07 10:07:41',
				'updated_at' => '2014-09-16 20:41:24',
			),
			10 => 
			array (
				'id' => '11',
				'dealer_id' => NULL,
				'name' => 'Becky Grossman',
				'initials' => NULL,
				'username' => 'beckyg',
				'password' => '$2y$10$z.XZXvv9H4PUIIRLhqcdmevCeDmg1fEhNrXiKJLgT9SkPsIuW3h1K',
				'email' => 'beckyg@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => 'imIppCRn21uO0duRBWI1bZ23oSX3imIiuesTjuovu2s7Zo9z5fGYCYqHYikx',
				'active' => '1',
				'created_at' => '2014-08-07 10:21:37',
				'updated_at' => '2014-08-13 08:47:30',
			),
			11 => 
			array (
				'id' => '14',
				'dealer_id' => '8',
				'name' => 'Ivory Dealer',
				'initials' => NULL,
				'username' => 'ivorydealer',
				'password' => '$2y$10$yIh3ZdYcjxsGMRAUCWz9IutmMZ8t2ChmvxWJVxKLex4BQI.AOg13O',
				'email' => 'ivorychevrolet@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => 'a3weVoxVqvWs3jq2iiIhV5DhWYfSfFVAGpH0XkGPnVHFixA7oUr21ExYnLTd',
				'active' => '1',
				'created_at' => '2014-08-29 15:35:00',
				'updated_at' => '2014-09-04 11:03:31',
			),
			12 => 
			array (
				'id' => '15',
				'dealer_id' => NULL,
				'name' => 'Mike Hankins',
				'initials' => 'MH',
				'username' => 'mike',
				'password' => '$2y$10$.C4dJpKvr1.hrNNxOaa2SOqGe/Vd9ZbxuOuHmZVKYqEUEEV9Wh6ee',
				'email' => 'mike@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => 'GMuC3QgnzCRhP3ck3qV8eoIltXF5OcOf2tReqcOkyUbyBRRnHQKQvg5WPrtl',
				'active' => '1',
				'created_at' => '2014-09-08 17:40:31',
				'updated_at' => '2014-09-26 12:20:41',
			),
			13 => 
			array (
				'id' => '16',
				'dealer_id' => NULL,
				'name' => 'Lester Ariel Mesa',
				'initials' => 'LAM',
				'username' => 'lesterm',
				'password' => '$2y$10$1a6juee8dZmum3Oe12TtVurcdO2UQOmIgm5.OXzvoJNCebQf/ggme',
				'email' => 'lesterm@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => 'rkprRFmI8jez0QDMAaYAouLEXqygKVChKoLSiUKjHL2RKr5vZIyOxpdDJcmD',
				'active' => '1',
				'created_at' => '2014-09-08 23:17:44',
				'updated_at' => '2014-11-18 08:52:04',
			),
			14 => 
			array (
				'id' => '17',
				'dealer_id' => NULL,
				'name' => 'Andrew DiAlberto',
				'initials' => 'AD',
				'username' => 'andrew',
				'password' => '$2y$10$1.Mk4bGLVCylGqjC1EOft.PBxmQYLHZ8de9xePSph1DXY6dvyX7xW',
				'email' => 'andrew1@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => 'vPm9s6OVFXmuHTLUKeJVAcdfESGg2cmC6zX3VHubUELhLIkvASBtHMPW51rC',
				'active' => '1',
				'created_at' => '2014-09-10 17:12:53',
				'updated_at' => '2014-12-23 17:50:54',
			),
			15 => 
			array (
				'id' => '18',
				'dealer_id' => NULL,
				'name' => 'Bernard Smalls',
				'initials' => 'BS',
				'username' => 'bernard',
				'password' => '$2y$10$CXfNHtpj7sO22unouHy7POPOdfxIMd2sR.fL5U53cTiK4kWLA97UK',
				'email' => 'bernardss1@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => NULL,
				'active' => '1',
				'created_at' => '2014-09-10 23:45:59',
				'updated_at' => '2014-12-23 17:52:57',
			),
			16 => 
			array (
				'id' => '19',
				'dealer_id' => NULL,
				'name' => 'Joe Trotta',
				'initials' => 'JT',
				'username' => 'joet',
				'password' => '$2y$10$1a6juee8dZmum3Oe12TtVurcdO2UQOmIgm5.OXzvoJNCebQf/ggme',
				'email' => 'joett1@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => 'No02Cb7GQgYzf7VM0Qkzd6q47bHr79UiXBLuYxoQoDRT1viCYhHoBWhXvn9p',
				'active' => '1',
				'created_at' => '2014-10-22 15:46:15',
				'updated_at' => '2014-12-23 17:53:13',
			),
			17 => 
			array (
				'id' => '21',
				'dealer_id' => NULL,
				'name' => 'Larissa Fredmonski ',
				'initials' => 'LF',
				'username' => 'larissa',
				'password' => '$2y$10$uYkn6Gj4uhixPzEzPIBQ2uuiRmykSMzh87hTT8Ega/3jgP4HJkO.C',
				'email' => 'larissa@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => 'FL',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => 'BwAoS5bBoCfWWBJa9SE2ql2dZP1tHSiwXCdi4sxuXSR0qRQzdZUTitzJS6Qz',
				'active' => '1',
				'created_at' => '2014-10-29 10:52:54',
				'updated_at' => '2014-12-29 17:42:02',
			),
			18 => 
			array (
				'id' => '22',
				'dealer_id' => NULL,
				'name' => 'Mike Lash',
				'initials' => NULL,
				'username' => 'mikel@loyaldriver.com',
				'password' => '$2y$10$JnjvShKlPitbt7o9P5Sih.5RLMPnPWH57gEZJ82vf2IqYEvmXIC7O',
				'email' => 'mikell1@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => 'FZTTlBFQOMgm13cjMX72X8sHGjlmqeA5ZVl50LTKNAZycprprPGUYawCfK52',
				'active' => '1',
				'created_at' => '2014-11-11 20:50:50',
				'updated_at' => '2014-12-23 17:53:31',
			),
			19 => 
			array (
				'id' => '23',
				'dealer_id' => NULL,
				'name' => 'Dick Bokavich',
				'initials' => NULL,
				'username' => 'dickb@loyaldriver.com',
				'password' => '$2y$10$vobxbTMrZ3gSnCfUE2GuwOLmrsSnM77Y3QPo1iD/9MZTJ94Y1l/Ti',
				'email' => 'dickbb1@loyaldriver.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => NULL,
				'active' => '1',
				'created_at' => '2014-11-11 20:57:56',
				'updated_at' => '2014-12-23 17:53:45',
			),
			20 => 
			array (
				'id' => '24',
				'dealer_id' => NULL,
				'name' => 'Alejandro Torres',
				'initials' => NULL,
				'username' => 'aroliva3@gmail.com',
				'password' => '$2y$10$XxVD.oda.QjEzM2cBbC0y.PrdHS.6BlB0fcHrWeehUK.0u8dH7lVS',
				'email' => 'aroliva3@gmail.com',
				'address_1' => '',
				'address_2' => '',
				'city' => '',
				'state' => '',
				'zip' => '',
				'phone' => '',
				'fax' => '',
				'remember_token' => NULL,
				'active' => '1',
				'created_at' => '2015-01-10 08:26:28',
				'updated_at' => '2015-01-10 08:26:28',
			),
		));
	}

}
